/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

//import Maintenance.CleaningPanel;
import Common.JpanelLoader;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import SetOfModels.SetOfStations;

/**
 *
 * @author Himal Madhushan
 */
public class Home extends javax.swing.JFrame {

    private Vector<Vector<String>> data; 
    private Vector<String> header;
    SetOfStations allStations = new SetOfStations();
    JpanelLoader loader = new JpanelLoader();
//    private SetOfUsers allUsers = new SetOfUsers();
    
    /**
     * Creates new form Home
     */
    public Home() throws ClassNotFoundException, IOException {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnHome = new javax.swing.JButton();
        btnClearning = new javax.swing.JButton();
        btnTraffic = new javax.swing.JButton();
        btnParking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoadingPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFlood = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, -1, 750));

        btnHome.setBackground(new java.awt.Color(0, 51, 102));
        btnHome.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Mothership");
        btnHome.setBorderPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 70));

        btnClearning.setBackground(new java.awt.Color(0, 51, 102));
        btnClearning.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        btnClearning.setForeground(new java.awt.Color(255, 255, 255));
        btnClearning.setText("Cleaning");
        btnClearning.setBorderPainted(false);
        btnClearning.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClearning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearningActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearning, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 70));

        btnTraffic.setBackground(new java.awt.Color(0, 51, 102));
        btnTraffic.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        btnTraffic.setForeground(new java.awt.Color(255, 255, 255));
        btnTraffic.setText("Paramedic");
        btnTraffic.setBorderPainted(false);
        btnTraffic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrafficActionPerformed(evt);
            }
        });
        jPanel1.add(btnTraffic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 230, 70));

        btnParking.setBackground(new java.awt.Color(0, 51, 102));
        btnParking.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        btnParking.setForeground(new java.awt.Color(255, 255, 255));
        btnParking.setText("Parking");
        btnParking.setBorderPainted(false);
        btnParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParkingActionPerformed(evt);
            }
        });
        jPanel1.add(btnParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 230, 70));

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(184, 189, 141));
        jLabel1.setText("Smart City Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 470, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Time");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        LoadingPanel.setBackground(new java.awt.Color(0, 51, 102));
        LoadingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        LoadingPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        jPanel1.add(LoadingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 1030, 700));

        btnFlood.setBackground(new java.awt.Color(0, 51, 102));
        btnFlood.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        btnFlood.setForeground(new java.awt.Color(255, 255, 255));
        btnFlood.setText("Flood");
        btnFlood.setBorderPainted(false);
        btnFlood.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloodActionPerformed(evt);
            }
        });
        jPanel1.add(btnFlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        try {
            MothershipPanel mothership = new MothershipPanel();
            loader.jPanelLoader(LoadingPanel, mothership);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnClearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearningActionPerformed
        try {
            CleaningPanel ss = new CleaningPanel();
            loader.jPanelLoader(LoadingPanel, ss);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClearningActionPerformed

    private void btnTrafficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrafficActionPerformed

        try {
            ParamedicHomePanel para = new ParamedicHomePanel();
            loader.jPanelLoader(LoadingPanel, para);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTrafficActionPerformed

    private void btnParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParkingActionPerformed
        try {
            ParkingPanel parking = new ParkingPanel();
            loader.jPanelLoader(LoadingPanel, parking);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnParkingActionPerformed

    private void btnFloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloodActionPerformed
        try {
            FloodPanel ss = new FloodPanel();
            loader.jPanelLoader(LoadingPanel, ss);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFloodActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoadingPanel;
    private javax.swing.JButton btnClearning;
    private javax.swing.JButton btnFlood;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnParking;
    private javax.swing.JButton btnTraffic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
