/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Common.JpanelLoader;
import Models.SensorStation;
import Serialize.FileName;
import Serialize.Serialization;
import SetOfModels.SetOfStations;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Himal Madhushan
 */
public class MothershipPanel extends javax.swing.JPanel {

    private Vector<Vector<String>> data; 
    private Vector<String> header;
    SetOfStations allStations = new SetOfStations();
    JpanelLoader loader = new JpanelLoader();
    
    /**
     * Creates new form MothershipPanel
     */
    public MothershipPanel() throws ClassNotFoundException, IOException {
        initComponents();
        loadStations();
    }

    private void loadStations() throws ClassNotFoundException, IOException  {
        allStations.removeAllElements();
        try {
            allStations.addAll(Serialization.deserializeParkingStations());
            System.out.println("MothershipPanel 1 : "+allStations);
            
        } catch (IOException e) {
        }
        try {
            allStations.addAll(Serialization.deserializeCleaningStations());
            System.out.println("MothershipPanel 2 : "+allStations);
            
        } catch (IOException e) {
        }
        try {
            allStations.addAll(Serialization.deserializeTrafficStations());
            System.out.println("MothershipPanel 3 : "+allStations);
            
        } catch (IOException e) {
        }
        try {
            allStations.addAll(Serialization.deserializeFloodStations());
            System.out.println("MothershipPanel 4 : "+allStations);
            
        } catch (IOException e) {
        }
        this.loadStationsTable();
    }
    
    private void loadStationsTable() {
        data = new Vector<Vector<String>>();
        header = new Vector<String>();

        header.add("ID");
        header.add("Station Name");
        header.add("Location");
        header.add("Department");

        for (SensorStation station : allStations) {
            Vector v = new Vector();
            v.add(station.getStationName());
            v.add(station.getStationID());
            v.add(station.getStationLocationName());
            v.add(station.getStationType().toString());
            data.add(v);
        }
        tblStations.setModel(new DefaultTableModel(data, header));
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblStations.getModel());
        tblStations.setRowSorter(sorter);
        scrollSensors.setViewportView(tblStations);
        tblStations.setAutoCreateRowSorter(true);
        tblStations.setAutoscrolls(true);
        tblStations.getTableHeader().setReorderingAllowed(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        scrollSensors = new javax.swing.JScrollPane();
        tblStations = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollSensors.setViewportView(tblStations);

        jPanel2.add(scrollSensors, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 990, 510));

        jButton1.setText("Add Station");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 150, -1));

        jButton2.setText("Remove Station");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            AddStationForm adsStation = new AddStationForm();
            adsStation.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MothershipPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MothershipPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrollSensors;
    private javax.swing.JTable tblStations;
    // End of variables declaration//GEN-END:variables
}
