/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Clock;
import Models.SensorMonitor;
import Serialize.FileName;
import java.io.DataInputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Serialize.Serialization;
import SetOfModels.SetOfSensorMonitors;
import java.awt.Component;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import Models.ParkingSlot;
import Models.SensorStation;
import Models.SensorType;
import SetOfModels.SetOfStations;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
/**
 *
 * @author Sanduni
 */
public class ParkingPanel extends javax.swing.JPanel {

    private Vector<Vector<String>> data; 
    private Vector<String> header;
    SetOfSensorMonitors sensorMonitors = new SetOfSensorMonitors();
    SetOfStations allStations = new SetOfStations();
    SensorStation selectedStation;
    
    /**
     * Creates new form ParkingPanel
     */
    public ParkingPanel() throws ClassNotFoundException, IOException {
        initComponents();
        this.loadStations();
        loadSensorMonitorsTable();
    }

    private void loadStations() throws ClassNotFoundException, IOException  {
        try {
            allStations.addAll(Serialization.deserializeParkingStations());
            this.fillComboBox();
        } catch (IOException e) {
            Serialization.Serializing(allStations, FileName.STATION_PARKING);
        }
    }
    
    private void fillComboBox() {
        cmbStations.removeAllItems();
        for (SensorStation station : allStations) {
            cmbStations.addItem(station);
        }
    }
    
    private void loadSensorMonitorsTable() {
        if (this.selectedStation == null) {
            return;
        }
        sensorMonitors.removeAllElements();
        for (SensorMonitor monitor: selectedStation.getSensorsMonitors()) {
            sensorMonitors.add(monitor);
        }
        
        data = new Vector<Vector<String>>();
        header = new Vector<String>();

        header.add("Slot No");
        header.add("Slot ID");
        header.add("Slot Type");
        header.add("Price");

        for (SensorMonitor monitor : sensorMonitors) {
            ParkingSlot slot = (ParkingSlot) monitor;
            Vector v = new Vector();
            v.add(slot.getSlot_name());
            v.add(slot.getSensorMonitorID());
            v.add(slot.getSuitable());
            v.add(slot.getPrice());
            data.add(v);
        }
        
        tblSensors.setModel(new DefaultTableModel(data, header));
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblSensors.getModel());
        tblSensors.setRowSorter(sorter);
        scrollSensors.setViewportView(tblSensors);
        tblSensors.setAutoCreateRowSorter(true);
        tblSensors.setAutoscrolls(true);
        tblSensors.getTableHeader().setReorderingAllowed(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSlotNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSlotId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbSuitable = new javax.swing.JComboBox<>();
        btnAddSlotSensor = new javax.swing.JButton();
        btnDemo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        scrollSensors = new javax.swing.JScrollPane();
        tblSensors = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbStations = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 51, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 102));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Parking Slot");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 280, 30));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Slot Number :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 120, -1));

        txtSlotNo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        txtSlotNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlotNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSlotNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 370, 30));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sensor ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 80, -1));

        txtSlotId.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jPanel1.add(txtSlotId, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 370, 30));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(" Price :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 80, 30));

        txtPrice.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        txtPrice.setEnabled(false);
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 370, 30));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Suitable for :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 120, 20));

        cmbSuitable.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        cmbSuitable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor Bike", "Car", "Heavy Vehicles" }));
        cmbSuitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSuitableActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSuitable, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 370, 30));

        btnAddSlotSensor.setBackground(new java.awt.Color(0, 51, 102));
        btnAddSlotSensor.setFont(new java.awt.Font("Avenir Next", 1, 12)); // NOI18N
        btnAddSlotSensor.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSlotSensor.setText("Add Slot");
        btnAddSlotSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSlotSensorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSlotSensor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 220, 40));

        btnDemo.setBackground(new java.awt.Color(0, 51, 102));
        btnDemo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        btnDemo.setForeground(new java.awt.Color(255, 255, 255));
        btnDemo.setText("Demo");
        btnDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 90, 30));

        jTabbedPane1.addTab("New Slots", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Reports");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jTabbedPane1.addTab("Reports", jPanel4);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSensors.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        tblSensors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollSensors.setViewportView(tblSensors);

        jPanel2.add(scrollSensors, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 980, 470));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Slot Summary");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 210, -1));

        jTabbedPane1.addTab("Parking Slots", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1020, 620));

        jLabel8.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Station");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmbStations.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        cmbStations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStationsActionPerformed(evt);
            }
        });
        add(cmbStations, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 310, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void txtSlotNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlotNoActionPerformed
        
    }//GEN-LAST:event_txtSlotNoActionPerformed
    
    private void btnAddSlotSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSlotSensorActionPerformed
        
        if (this.selectedStation == null) {
            System.out.println("No selected station");
            return;
        }
        System.out.println("selectedStation monitors: "+ selectedStation.getSensorsMonitors());
        
        String slot_name = this.txtSlotNo.getText();
        String sensor_ID = this.txtSlotId.getText();
        String suitable = this.cmbSuitable.getSelectedItem().toString();
        String price = this.txtPrice.getText();
        
        ArrayList<Double> coords = new ArrayList<Double>();
        coords.add(69.786732);
        coords.add(81.340522);
        
        ParkingSlot slot = new ParkingSlot(sensor_ID, coords, true, SensorType.FLOOD);
        slot.setSlot_name(slot_name);
        slot.setSuitable(suitable);
        slot.setPrice(price);
        this.selectedStation.addNewSensorMonitor(slot);
        
        try {
            Serialization.Serializing(allStations, FileName.STATION_PARKING);
        } catch (IOException ex) {
            Logger.getLogger(ParkingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadSensorMonitorsTable();
        
//        Clock.getInstance().registerObserver(slot);
    }//GEN-LAST:event_btnAddSlotSensorActionPerformed

    
    
    private void btnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoActionPerformed
        txtSlotNo.setText("F 01");
        txtSlotId.setText("Sensor 01");
        cmbSuitable.setSelectedIndex(1);
    }//GEN-LAST:event_btnDemoActionPerformed

    private void cmbStationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStationsActionPerformed
        selectedStation = (SensorStation) cmbStations.getSelectedObjects()[0];
        loadSensorMonitorsTable();
    }//GEN-LAST:event_cmbStationsActionPerformed

    private void cmbSuitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSuitableActionPerformed
        if (cmbSuitable.getSelectedIndex() == 0) {
            txtPrice.setText("20.00");
        } else if (cmbSuitable.getSelectedIndex() == 1) {
            txtPrice.setText("50.00");
        } else if (cmbSuitable.getSelectedIndex() == 2) {
            txtPrice.setText("80.00");
        }
    }//GEN-LAST:event_cmbSuitableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSlotSensor;
    private javax.swing.JButton btnDemo;
    private javax.swing.JComboBox cmbStations;
    private javax.swing.JComboBox<String> cmbSuitable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane scrollSensors;
    private javax.swing.JTable tblSensors;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSlotId;
    private javax.swing.JTextField txtSlotNo;
    // End of variables declaration//GEN-END:variables

}
