/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;

import SetOfModels.SetOfUsers;
import Models.User;
import Serialize.FileName;
import Serialize.Serialization;
/**
 *
 * @author Praweenkg
 */
public class RegisterForm1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public User smartCityUser;
    static User logperson_disasterManagement;
    static User logperson_parkignManagement;
    static User logperson_ambulanceService;
    static User logperson_cityCleaning;

    int email_status = 0;
    int password_status = 0;
    int nic_status = 0;
    
    // Purple color
    Color mypurple = new Color(122,72,221);
    
    private SetOfUsers allUsers = new SetOfUsers();

    public RegisterForm1() throws ClassNotFoundException, IOException{
        initComponents();
        this.refreshData();
    }
    
    private void refreshData() throws ClassNotFoundException, IOException  {
        try {
            allUsers.addAll(Serialization.deserializeUsers());

            System.out.println("users: " + allUsers);
        } catch (IOException e) {
            Serialization.Serializing(allUsers, FileName.USER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        register_buttonRegiater = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        txtJobTitle = new javax.swing.JTextField();
        cmbUserDepartment = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordRepeat = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        register_email1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        register_buttonDemo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(0, 51, 102));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 500, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Username (Email):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 76, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("First Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 116, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        txtFirstName.setBackground(new java.awt.Color(0, 51, 102));
        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(null);
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 112, 500, 30));

        txtLastName.setBackground(new java.awt.Color(0, 51, 102));
        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtLastName.setBorder(null);
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 152, 500, 30));

        register_buttonRegiater.setBackground(new java.awt.Color(0, 51, 102));
        register_buttonRegiater.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        register_buttonRegiater.setForeground(new java.awt.Color(255, 255, 255));
        register_buttonRegiater.setText("Register");
        register_buttonRegiater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonRegiaterActionPerformed(evt);
            }
        });
        getContentPane().add(register_buttonRegiater, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 500, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Category:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Job Title:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("NIC:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        txtNIC.setBackground(new java.awt.Color(0, 51, 102));
        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNIC.setForeground(new java.awt.Color(255, 255, 255));
        txtNIC.setBorder(null);
        txtNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNICFocusLost(evt);
            }
        });
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
        });
        getContentPane().add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 272, 500, 30));

        txtJobTitle.setBackground(new java.awt.Color(0, 51, 102));
        txtJobTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtJobTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtJobTitle.setBorder(null);
        getContentPane().add(txtJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 312, 500, 30));

        cmbUserDepartment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbUserDepartment.setForeground(new java.awt.Color(51, 51, 51));
        cmbUserDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disaster Management", "Parking Management", "Ambulance Service ", "City Cleaning Service" }));
        getContentPane().add(cmbUserDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 352, 500, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Repeat Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 20));

        txtPassword.setBackground(new java.awt.Color(0, 51, 102));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 192, 500, 30));

        txtPasswordRepeat.setBackground(new java.awt.Color(0, 51, 102));
        txtPasswordRepeat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPasswordRepeat.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordRepeat.setBorder(null);
        txtPasswordRepeat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordRepeatFocusLost(evt);
            }
        });
        getContentPane().add(txtPasswordRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 232, 500, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 500, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 500, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 500, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 500, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 500, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 500, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 500, 10));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Account");
        jPanel2.add(jLabel10);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 480));

        jToggleButton1.setBackground(new java.awt.Color(255, 51, 51));
        jToggleButton1.setSelected(true);
        jToggleButton1.setText("X");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        register_email1.setBackground(new java.awt.Color(122, 72, 221));
        register_email1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        register_email1.setForeground(new java.awt.Color(255, 255, 255));
        register_email1.setBorder(null);
        register_email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                register_email1FocusLost(evt);
            }
        });
        register_email1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                register_email1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                register_email1KeyTyped(evt);
            }
        });
        getContentPane().add(register_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 500, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_buttonDemo.setText("Demo");
        register_buttonDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonDemoActionPerformed(evt);
            }
        });
        jPanel1.add(register_buttonDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 630, 420));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setForeground(new java.awt.Color(122, 72, 221));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" ");
        jPanel3.add(jLabel9);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 630, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void register_buttonRegiaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonRegiaterActionPerformed

        if (txtFirstName.getText().isEmpty() == false && txtLastName.getText().isEmpty() == false && txtEmail.getText().isEmpty() == false && txtPassword.getText().isEmpty() == false) {
            if (allUsers.userExists(txtEmail.getText())) {
                JOptionPane.showMessageDialog(null, "SORRY! " + txtEmail.getText() + ", Already exists!\n Try again. ", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                User user = new User(txtEmail.getText(), txtPassword.getText(), txtFirstName.getText(), txtLastName.getText());
                user.userDepartment = cmbUserDepartment.getSelectedItem().toString();
                allUsers.add(user);
                try {
                    this.refreshData();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(RegisterForm1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(RegisterForm1.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    Serialization.Serializing(allUsers, FileName.USER);
                } catch (IOException e) {}
            }
        }
    }//GEN-LAST:event_register_buttonRegiaterActionPerformed

    private void txtNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNICFocusLost


    }//GEN-LAST:event_txtNICFocusLost

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        String email = txtEmail.getText();
        Color mywhite = new Color(255,255,255);
        if (!email.contains("@")) {
            email_status = 1;
            txtEmail.setBackground(Color.red);

        } else {
            email_status = 0;
            txtEmail.setBackground(Color.white);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFocusLost

    private void register_buttonDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonDemoActionPerformed
        txtFirstName.setText("Himal");
        txtLastName.setText("Madhushan");
        txtEmail.setText("macka@macka.com");
        txtPassword.setText("123");
        txtPasswordRepeat.setText("123");
        txtNIC.setText("123");
        txtJobTitle.setText("SE");
        // TODO add your handling code here:
    }//GEN-LAST:event_register_buttonDemoActionPerformed

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String Password = txtPassword.getText();
        String Password2 = txtPasswordRepeat.getText();
        if (!Password.matches(Password2)) {
            password_status = 1;
            txtPassword.setBackground(Color.red);
            txtPasswordRepeat.setBackground(Color.red);

        } else {
            password_status = 0;
            txtPassword.setBackground(Color.white);
            txtPasswordRepeat.setBackground(Color.white);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordRepeatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordRepeatFocusLost
        String Password = txtPassword.getText();
        String Password2 = txtPasswordRepeat.getText();
        if (!Password.matches(Password2)) {
            password_status = 1;
            txtPassword.setBackground(Color.red);
            txtPasswordRepeat.setBackground(Color.red);

        } else {
            password_status = 0;
            txtPassword.setBackground(Color.white);
            txtPasswordRepeat.setBackground(Color.white);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordRepeatFocusLost

    private void register_email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_register_email1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_register_email1FocusLost

    private void register_email1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_register_email1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_register_email1KeyReleased

    private void register_email1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_register_email1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_register_email1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisterForm1().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(RegisterForm1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(RegisterForm1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbUserDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton register_buttonDemo;
    private javax.swing.JButton register_buttonRegiater;
    private javax.swing.JTextField register_email1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtJobTitle;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordRepeat;
    // End of variables declaration//GEN-END:variables
}
